export const commentsData = [
  {
    author: "Naresh Baleboina",
    id: Math.random(),
    content: "This is first comment",
    votes: 0,
    timeStamp: new Date().toISOString(),
    replies: [
      {
        author: "Naresh Baleboina",
        id: Math.random(),
        content: "This is first comment reply 1",
        votes: 0,
        timeStamp: new Date().toISOString(),
        replies: [],
      },
      {
        author: "Naresh Baleboina",
        id: Math.random(),
        content: "This is first comment reply 2",
        votes: 0,
        timeStamp: new Date().toISOString(),
        replies: [],
      },
      {
        author: "Naresh Baleboina",
        id: Math.random(),
        content: "This is first comment reply 3",
        votes: 0,
        timeStamp: new Date().toISOString(),
        replies: [
          {
            author: "Naresh Baleboina",
            id: Math.random(),
            content: "This is first comment reply 3 reply 1",
            votes: 0,
            timeStamp: new Date().toISOString(),
            replies: [],
          },
          {
            author: "Naresh Baleboina",
            id: Math.random(),
            content: "This is first comment reply 3 reply 2",
            votes: 0,
            timeStamp: new Date().toISOString(),
            replies: [],
          },
          {
            author: "Naresh Baleboina",
            id: Math.random(),
            content: "This is first comment reply 3 reply 3",
            votes: 0,
            timeStamp: new Date().toISOString(),
            replies: [],
          },
        ],
      },
    ],
  },
  {
    author: "Naresh Baleboina",
    id: Math.random(),
    content: "This is second comment",
    votes: 0,
    timeStamp: new Date().toISOString(),
    replies: [],
  },
  {
    author: "Naresh Baleboina",
    id: Math.random(),
    content: "This is third comment",
    votes: 0,
    timeStamp: new Date().toISOString(),
    replies: [
      {
        author: "Naresh Baleboina",
        id: Math.random(),
        content: "This is third comment reply 1",
        votes: 0,
        timeStamp: new Date().toISOString(),
        replies: [],
      },
      {
        author: "Naresh Baleboina",
        id: Math.random(),
        content: "This is third comment reply 2",
        votes: 0,
        timeStamp: new Date().toISOString(),
        replies: [],
      },
      {
        author: "Naresh Baleboina",
        id: Math.random(),
        content: "This is third comment reply 3",
        votes: 0,
        timeStamp: new Date().toISOString(),
        replies: [],
      },
    ],
  },
  {
    author: "Naresh Baleboina",
    id: Math.random(),
    content: "This is fourth comment",
    votes: 0,
    timeStamp: new Date().toISOString(),
    replies: [],
  },
  {
    author: "Naresh Baleboina",
    id: Math.random(),
    content: "This is fifth comment",
    votes: 0,
    timeStamp: new Date().toISOString(),
    replies: [],
  },
  {
    author: "Naresh Baleboina",
    id: Math.random(),
    content: "This is sixth comment",
    votes: 0,
    timeStamp: new Date().toISOString(),
    replies: [],
  },
];
